#index:
#    path: /
#    controller: App\Controller\DefaultController::index

Main:
    resource: App\Controller\MainController
    type: annotation
User:
    resource: App\Controller\UserController
    type: annotation
Security:
    resource: App\Controller\SecurityController
    type: annotation
Category:
    resource: App\Controller\CategoryController
    type: annotation
Tool:
    resource: App\Controller\ToolController
    type: annotation
Information:
    resource: App\Controller\InformationController
    type: annotation
NoticeParagraph:
    resource: App\Controller\NoticeParagraphController
    type: annotation
Question:
    resource: App\Controller\QuestionController
    type: annotation
Consumable:
    resource: App\Controller\ConsumableController
    type: annotation

